application: cesarjoaniquet
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /cat
  static_dir: cat

- url: /es
  static_dir: es

- url: /en
  static_dir: en

- url: /.*
  script: cesarjoaniquet.app

libraries:
- name: jinja2
  version: latest